[package]
name = "nds-io-cli"
version = "0.1.0"
edition = "2021"
authors = ["Aetias <aetias@outlook.com>"]
license = "MIT"
repository = "https://github.com/AetiasHax/nds-io"
readme = "../README.md"
description = "Command-line interface for reading/writing Nintendo DS files."
publish = false

[[bin]]
name = "ndsio"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
nds-io = { path = "../lib" }
